- .gitattributes
- .github/copilot-instructions.md
- .markdownlint-cli2.yaml
- llms.txt
- Introduced a new documentation file for Sparkle development.
- Covers architecture overview, critical workflows, and project conventions.
- Provides detailed instructions for development commands and package patterns.
- Includes integration points and development tools used in the project.
> docs: add comprehensive development guide for Sparkle

- .ai/plan/feature-accessible-form-component-1.md
- .prettierignore
- .vscode/settings.json
- pnpm-workspace.yaml
- Outline development of a comprehensive, accessible Form component
- Leverage Radix UI primitives to ensure WCAG compliance
- Define core, accessibility, testing, documentation, architecture, performance, and design requirements
- Detail implementation phases and tasks for component development
- Include risks, assumptions, and related specifications for further reading
> docs(ui): add implementation plan for accessible Form component

- .ai/notes/radix-form-architecture-decisions.md
- .ai/plan/feature-accessible-form-component-1.md
- packages/types/src/index.ts
- packages/ui/package.json
- packages/ui/src/components/Form/Form.tsx
- packages/ui/src/components/Form/FormControl.tsx
- packages/ui/src/components/Form/FormField.tsx
- packages/ui/src/components/Form/FormLabel.tsx
- packages/ui/src/components/Form/FormMessage.tsx
- packages/ui/src/components/Form/FormSelect.tsx
- packages/ui/src/components/Form/FormTextarea.tsx
- packages/ui/src/components/Form/index.ts
- packages/ui/src/components/index.ts
- pnpm-lock.yaml
- Add Form, FormField, FormLabel, FormControl, FormMessage, FormTextarea, and FormSelect components
- Extend FieldProps with FormFieldProps and FormMessageProps for validation
- Update package.json to include Radix UI dependencies
- Create architectural decision document for form implementation
- Update implementation plan to reflect progress and tasks completion
Closes #775.
> feat(ui): implement accessible Form component using Radix UI

- .ai/plan/feature-accessible-form-component-1.md
- packages/ui/src/components/Form/FormSubmit.tsx
- packages/ui/src/components/Form/index.ts
- Implement FormSubmit component using Radix UI primitives
- Update index.ts to export FormSubmit for individual imports
- Ensure proper form association and styling variants for the submit button
Closes #776.
> feat(ui): add FormSubmit component for form submission

- .ai/plan/feature-accessible-form-component-1.md
- .github/workflows/main.yaml
- packages/storybook/package.json
- packages/storybook/src/stories/Form.stories.tsx
- packages/storybook/tsconfig.json
- pnpm-lock.yaml
- Add Form.stories.tsx to showcase various form configurations
- Update implementation plan with completed tasks and dates
- Include @sparkle/ui as a dependency in package.json
- Enhance tsconfig.json to include additional paths and references
- Update pnpm-lock.yaml to reflect dependency changes
Closes #779.
> feat(storybook): add Form component stories

- .ai/plan/feature-accessible-form-component-1.md
- package.json
- packages/storybook/.storybook/main.ts
- packages/storybook/package.json
- packages/ui/README.md
- pnpm-lock.yaml
- scripts/accessibility-audit.sh
- Update status to 'Completed' in the implementation plan
- Add comprehensive usage documentation for the Form component
- Include accessibility features and validation states in the README
- Integrate axe-core and Lighthouse audits in a new accessibility script
- Add @storybook/addon-a11y for accessibility testing in Storybook
- Update package.json with new dependencies for accessibility tools
Closes #780.
> feat(ui): complete implementation of accessible Form component

- .github/actions/setup-ci/action.yaml
- package.json
- packages/config/package.json
- packages/config/tsdown.config.ts
- packages/error-testing/package.json
- packages/error-testing/tsdown.config.ts
- packages/types/package.json
- packages/types/tsdown.config.ts
- packages/utils/package.json
- packages/utils/tsdown.config.ts
- pnpm-lock.yaml
- replace tsc with tsdown in package.json scripts for multiple packages
- add tsdown configuration files for new build process
- update CI action to cache tsdown output
> feat: migrate build scripts to tsdown for improved performance

- .github/copilot-instructions.md
- Add guidelines for using tsdown as the primary build tool
- Outline code style conventions and utility types usage
- Specify documentation standards for public APIs
- Introduce error handling and logging best practices
- Recommend type-safe testing strategies with Vitest
> docs(copilot-instructions): enhance TypeScript section

- .ai/plan/feature-theme-management-package-1.md
- packages/theme/src/index.ts
- packages/theme/src/tokens/base.ts
- packages/theme/src/tokens/dark.ts
- packages/theme/src/tokens/light.ts
- packages/theme/src/tokens/native.ts
- packages/theme/src/tokens/web.ts
- packages/theme/src/utils/token-transformer.ts
- packages/theme/src/validators/theme-validator.ts
- packages/types/src/index.ts
- pnpm-workspace.yaml
- Introduced `generateCSSVariables` and `cssPropertiesToString` functions for generating CSS custom properties from design tokens.
- Implemented `TokenTransformer` class for cross-platform token transformation between web and native formats.
- Added `ThemeValidator` class for validating theme configurations, ensuring integrity and accessibility compliance.
- Enhanced `ThemeConfig` type with detailed interfaces for colors, typography, spacing, shadows, border radius, and animations.
- Updated `pnpm-workspace.yaml` to include `chromedriver` in the onlyBuiltDependencies list.
Closes #799.
> feat: add comprehensive theme configuration and validation

- .ai/plan/feature-theme-management-package-1.md
- packages/theme/src/context/ThemeContext.tsx
- packages/theme/src/hooks/index.ts
- packages/theme/src/index.ts
- packages/theme/src/persistence/index.ts
- packages/theme/src/providers/NativeThemeProvider.tsx
- packages/theme/src/providers/ThemeProvider.tsx
- packages/theme/tsdown.config.ts
- Add ThemeContext for managing theme state across the application
- Create useTheme and useColorScheme hooks for easier theme access
- Implement NativeThemeProvider and ThemeProvider for React Native and web
- Add theme persistence utilities for localStorage and AsyncStorage
- Update tsdown configuration to include necessary external dependencies
Closes #800.
> feat: implement theme management with context and persistence

- .ai/plan/feature-theme-management-package-1.md
- packages/storybook/package.json
- packages/storybook/src/stories/Theme.stories.tsx
- pnpm-lock.yaml
- Create Theme.stories.tsx to showcase theme system features
- Document design tokens, theme modes, and semantic colors
- Provide usage examples for theme-aware components and styling
- Implement advanced theme switcher with visual feedback
Relates to TASK-029 on #802.
> feat: add comprehensive theme stories

- .ai/plan/feature-theme-management-package-1.md
- packages/fro-jive/app/_layout.tsx
- packages/fro-jive/package.json
- pnpm-lock.yaml
- Update RootLayout to wrap with NativeThemeProvider for theme management
- Update last_updated date in the implementation plan
- Add @sparkle/theme dependency to package.json
Closes #802.
> feat: integrate NativeThemeProvider into RootLayout

- .ai/plan/feature-theme-management-package-1.md
- Finalize the theme system with build optimizations, comprehensive testing, documentation, and production readiness
- Add comprehensive unit tests for all theme utilities and components using Vitest
- Create integration tests for theme persistence and system detection
- Implement visual regression tests for themed components in Storybook
- Optimize Turborepo build pipeline for theme package dependencies
- Create comprehensive documentation with examples and migration guide
- Set up changesets and prepare package for initial release
> docs: finalize theme system with implementation plan

- .ai/plan/feature-theme-management-package-1.md
- packages/theme/package.json
- packages/theme/src/react-native/index.ts
- packages/theme/src/tailwind/index.ts
- packages/theme/tsdown.config.ts
- packages/theme/vite.config.ts
- turbo.json
- Add React Native integration entry point with theme utilities
- Create Tailwind CSS integration entry point with essential utilities
- Update build configuration to include new entry points for Tailwind and React Native
- Optimize Turborepo tasks for theme package dependencies and testing
- Improve Vite configuration with coverage thresholds and sourcemaps
Relates to TASK-034 on #803.
> feat: enhance theme package with React Native and Tailwind support

- .ai/plan/feature-theme-management-package-1.md
- packages/theme/README.md
- packages/theme/docs/API.md
- packages/theme/docs/CONTRIBUTING.md
- packages/theme/docs/EXAMPLES.md
- packages/theme/docs/MIGRATION.md
- Introduced EXAMPLES.md with advanced usage patterns including custom theme creation, dynamic theme loading, cross-platform components, theme validation, performance optimization, and testing strategies.
- Added MIGRATION.md to assist users in transitioning from previous theme implementations to the new @sparkle/theme package, detailing breaking changes, migration steps, updated patterns, common issues, and migration examples.
Relates to TASK-035 on #803.
> docs(theme): add comprehensive examples and migration guide

- .ai/plan/feature-theme-management-package-1.md
- .changeset/config.json
- .changeset/initial-theme-release.md
- packages/theme/package.json
- pnpm-lock.yaml
- Update status to 'Completed' in the implementation plan
- Add initial release notes for @sparkle/theme v0.1.0
- Change access level to public in changeset configuration
- Enhance package.json with additional metadata and dependencies
Closes #803.
> chore: finalize theme package and prepare for initial release

- packages/storybook/src/stories/Form.stories.tsx
- tsconfig.json
- Add type annotations for onChange and onSubmit event handlers
- Improve type safety for form field interactions
> fix: add type annotations for event handlers in Form stories

- .ai/plan/infrastructure-build-pipeline-1.md
- packages/config/tsconfig.json
- packages/storybook/tsconfig.json
- packages/ui/tsconfig.json
- Audit and update TypeScript project references in packages/ui, packages/storybook, and packages/config
- Mark tasks as completed in the infrastructure build pipeline plan
Relates to TASK-002, TASK-003, TASK-004, TASK-005 on #838.
> chore: update TypeScript project references in configuration files

- .ai/plan/infrastructure-build-pipeline-1.md
- tsconfig.json
- Add references to TypeScript configuration for all packages
- Verify root tsconfig.json composite settings work correctly
Relates to TASK-006 on #838.
> chore: update TypeScript project references in tsconfig files

- .ai/analysis/task-008-turborepo-analysis.md
- .ai/plan/infrastructure-build-pipeline-1.md
- Mark TASK-008 as completed and add analysis date of 2025-09-05.
Relates to TASK-008 on #839.
> chore: update TASK-008 status to completed with analysis date

- .ai/plan/infrastructure-build-pipeline-1.md
- .github/actions/setup-ci/action.yaml
- turbo.json
- Add additional dependencies to the build task for improved modularity.
- Update global environment variables to include STORYBOOK_ENV.
- Refactor build tasks to ensure proper dependency management.
- Ensure build:storybook task includes necessary dependencies.
Relates to TASK-009 on #839.
> chore: enhance build task dependencies in turbo.json

- .github/settings.yml
- .github/workflows/main.yaml
- .github/workflows/renovate.yaml
- change required status check context from Build to Check
- rename job from Build to Check in CI workflow
> chore(repo): update CI workflow and branch protection settings

- .ai/plan/infrastructure-build-pipeline-1.md
- turbo.json
- Add new build tasks for utils, error testing, theme, config, ui, and storybook
- Optimize cache strategies by specifying inputs/outputs for each package type
- Update test and typecheck tasks to include additional inputs and cache settings
- Improve clean task outputs to include coverage and storybook-static directories
Relates to TASK-010 on #839.
> build: enhance task dependencies and cache strategies in turbo.json

- .ai/plan/infrastructure-build-pipeline-1.md
- turbo.json
- Remove dependency on build task for build:types to improve isolation
- Optimize task dependencies for better performance and cache management
Relates to TASK-011 on #839.
> chore: update task dependencies and cache strategies in turbo.json

- .ai/plan/infrastructure-build-pipeline-1.md
- package.json
- pnpm-lock.yaml
- scripts/validate-turbo.ts
- Add validation script for turbo.json configuration
- Include checks for task dependencies and package references
- Update package.json to include new check:turbo script
- Mark TASK-014 as completed in the implementation plan
Closes #839.
> chore: enhance turbo.json validation and update scripts

- .ai/plan/infrastructure-build-pipeline-1.md
- packages/config/tsdown.config.ts
- packages/error-testing/tsdown.config.ts
- packages/types/tsdown.config.ts
- packages/ui/src/index.ts
- packages/ui/tsdown.config.ts
- packages/ui/vite.config.ts
- packages/utils/tsdown.config.ts
- Add support for ESM format in tsdown configurations
- Enable source maps and clean output directory for better builds
- Externalize React ecosystem and internal Sparkle packages
- Update build tasks in infrastructure plan for improved performance
Relates to TASK-015, TASK-016, TASK-017 on #840.
> build: enhance tsdown configurations across multiple packages

- .ai/plan/infrastructure-build-pipeline-1.md
- package.json
- Add manypkg configuration to package.json
- Implement workspace protocol and license requirements
- Set default branch for consistency across packages
Relates to TASK-023 on #841.
> build: update manypkg configuration

- .ai/plan/infrastructure-build-pipeline-1.md
- package.json
- scripts/enhanced-error-reporter.ts
- scripts/enhanced-error-wrapper.ts
- Add EnhancedErrorReporter class for improved error formatting
- Create enhanced-error-reporter.ts for detailed error handling
- Introduce enhanced-error-wrapper.ts to wrap commands with error reporting
- Update package.json to include new check:enhanced script
- Enhance error reporting for TypeScript errors and build failures
Relates to TASK-026 on #841.
> feat: implement enhanced error reporting for build commands

- .ai/plan/infrastructure-build-pipeline-1.md
- package.json
- pnpm-lock.yaml
- test/README.md
- test/build-artifacts-and-cache.test.ts
- test/build-pipeline-performance.test.ts
- test/cross-package-types.test.ts
- test/development-workflow.test.ts
- test/incremental-build.test.ts
- test/workspace-consistency.test.ts
- Implemented `development-workflow.test.ts` to validate TypeScript watch mode, build watch mode, development server functionality, and hot reload capabilities.
- Created `incremental-build.test.ts` to verify TypeScript project references and incremental compilation efficiency.
- Established `workspace-consistency.test.ts` to ensure workspace integrity through manypkg checks, dependency validation, and proper package configurations.
Relates to TASK-027 on #841.
> feat(tests): add test suites for development workflow, incremental builds, and workspace consistency

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/src/assets/sparkle-logo.svg
- docs/src/content/docs/components/overview.md
- docs/src/content/docs/development/contributing.md
- docs/src/content/docs/error-testing/overview.md
- docs/src/content/docs/getting-started/installation.md
- docs/src/content/docs/getting-started/introduction.md
- docs/src/content/docs/getting-started/project-structure.md
- docs/src/content/docs/getting-started/quick-start.md
- docs/src/content/docs/index.mdx
- docs/src/content/docs/theme/overview.md
- docs/src/content/docs/types/overview.md
- docs/src/content/docs/utils/overview.md
- docs/src/styles/custom.css
- Add comprehensive documentation for the Sparkle Design System.
- Include installation, getting started, and project structure guides.
- Create detailed overviews for components, utilities, and types.
- Implement theme system documentation with design token architecture.
- Introduce custom CSS for theme customization and styling enhancements.
- Add new SVG logo and update index page with Sparkle branding.
Closes #871.
> docs: enhance Sparkle documentation and add new components

- .github/copilot-instructions.md
- llms.txt
- Add comprehensive guides for getting started, installation, and project structure
- Include contributing guidelines for the Sparkle Design System
- Update documentation site references and improve organization
- Introduce automated documentation generation scripts for components
> docs(ai): enhance documentation with new guides and structure

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/package.json
- docs/src/components/InteractiveButtonDemo.astro
- docs/src/components/ReactIntegrationDemo.astro
- docs/src/components/demos/ButtonDemo.tsx
- docs/src/content/docs/development/react-integration-test.mdx
- docs/tsconfig.json
- pnpm-lock.yaml
- Add React integration to Astro configuration
- Implement interactive button demo component
- Create React integration test page to verify functionality
- Update dependencies for React and TypeScript support
- Document configuration and usage for React components
Relates to TASK-017 on #873.
> feat(docs): enhance React integration and add interactive demos

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/src/content/docs/components/architecture.md
- docs/src/content/docs/components/reference.md
- docs/src/content/docs/error-testing/test-builder.md
- docs/src/content/docs/error-testing/testing-strategies.md
- docs/src/content/docs/theme/cross-platform.md
- docs/src/content/docs/theme/customization.md
- docs/src/content/docs/theme/design-tokens.md
- docs/src/content/docs/types/interfaces.md
- docs/src/content/docs/types/patterns.md
- docs/src/content/docs/utils/react-hooks.md
- docs/src/content/docs/utils/string-utilities.md
- Introduced a new section on Type Patterns covering component props, polymorphic components, discriminated unions, form types, theme tokens, and utility types.
- Added a detailed guide on custom React Hooks including useDebounce, useClickOutside, and useAsync with examples and use cases.
- Created a collection of string utility functions such as toKebabCase, truncate, slugify, and toTitleCase, along with usage examples and performance considerations.
Relates to TASK-025 on #874.
> feat(docs): add documentation for Type Patterns, React Hooks, and String Utilities

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- Update last_updated date to 2025-09-09
- Mark TASK-026 as completed with the date 2025-09-09
- Add hierarchical navigation for Getting Started and Core System documentation
- Organize UI Components and Form Components for better clarity
- Introduce new sections for Utilities & Tools, Interactive Features, and API Reference
Relates to TASK-026 on #874.
> feat(docs): update Astro Starlight documentation structure

- docs/src/content/docs/components/button.mdx
- docs/src/content/docs/components/form.mdx
- Update descriptions for clarity and completeness
- Add detailed features and usage guidelines for Button component
- Improve examples and add validation handling in Form component
- Enhance accessibility information and best practices for both components
Relates to TASK-028 on #874.
> docs: enhance Button and Form component documentation

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/src/content/docs/utils/advanced-patterns.md
- docs/src/content/docs/utils/overview.md
- docs/src/content/docs/utils/reference.md
- Update overview documentation for utility functions and React hooks
- Add detailed API reference for utility functions in the Sparkle Design System
- Include installation and quick start sections for better user guidance
- Document advanced usage patterns and testing strategies for utilities
Relates to TASK-030 on #874.
> docs: enhance utility functions documentation and add reference guide

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/src/components/AccessibleCodeBlock.tsx
- docs/src/components/interactive/CodeEditor.tsx
- docs/src/components/interactive/CopyButton.tsx
- docs/src/components/navigation/KeyboardNavigation.tsx
- docs/src/components/navigation/SkipNavigation.astro
- docs/src/components/navigation/index.ts
- docs/src/hooks/use-focus-management.ts
- docs/src/styles/sparkle-theme.css
- Add skip navigation component for improved site-wide accessibility
- Implement focus management hooks for better focus control
- Enhance keyboard navigation support in code editor and copy button
- Update styles for focus visibility on interactive elements
- Conduct accessibility audits and ensure WCAG 2.1 AA compliance
Relates to TASK-036 on #875.
> feat: enhance keyboard accessibility across components

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/src/components/layout/ContentArticle.astro
- docs/src/components/layout/ContentAside.astro
- docs/src/components/layout/ContentNavigation.astro
- docs/src/components/layout/ContentSection.astro
- docs/src/components/layout/PageMain.astro
- docs/src/components/layout/SemanticHeading.astro
- docs/src/components/layout/SkipNavigation.astro
- docs/src/content/docs/guides/heading-hierarchy.mdx
- docs/src/layouts/api.astro
- Add semantic components for article, section, aside, and navigation
- Implement skip navigation for improved accessibility
- Create guidelines for heading hierarchy and semantic HTML usage
- Introduce API documentation layout to enforce proper heading levels
- Update last updated dates in documentation plans
Relates to TASK-037 on #875.
> feat: enhance documentation structure and accessibility components

- .ai/plan/feature-moo-dang-shell-1.md
- Create initial implementation plan for the "moo-dang" web shell
- Outline requirements and constraints for the application
- Define implementation steps across multiple phases
- Specify dependencies and testing strategies for the project
> docs: add implementation plan for WASM-based web shell application

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/index.html
- apps/moo-dang/package.json
- apps/moo-dang/src/App.test.tsx
- apps/moo-dang/src/App.tsx
- apps/moo-dang/src/index.css
- apps/moo-dang/src/main.tsx
- apps/moo-dang/tailwind.config.ts
- apps/moo-dang/test/setup.ts
- apps/moo-dang/tsconfig.json
- apps/moo-dang/vite.config.ts
- docs/src/content/docs/getting-started/installation.md
- docs/src/content/docs/getting-started/quick-start.md
- docs/src/content/docs/theme/troubleshooting.md
- pnpm-lock.yaml
- tsconfig.json
- turbo.json
- Add index.html to serve as the entry point for the application
- Create package.json with scripts and dependencies for the project
- Implement App component with basic layout and theme provider
- Add global styles in index.css for consistent styling
- Set up main.tsx to render the App component
- Configure TypeScript settings in tsconfig.json for the project
- Create vite.config.ts for Vite configuration and build setup
- Update turbo.json to include build tasks for the moo-dang application
- Change status in implementation plan to 'In Progress' and update tasks
Relates to TASK-001, TASK-002, TASK-003, and TASK-005 on #941.
> feat: implement initial structure for WASM-based web shell application

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/commands.test.ts
- apps/moo-dang/src/shell/commands.ts
- apps/moo-dang/src/workers/shell.worker.ts
- Add implementation for basic shell commands including cd.
- Update command creation to integrate ShellEnvironment.
- Enhance command execution context with environment management.
- Modify tests to validate new cd command functionality.
Relates to TASK-016 on #943.
> feat: implement basic shell commands and integrate environment

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/parser.ts
- apps/moo-dang/src/shell/pipeline.test.ts
- apps/moo-dang/src/shell/pipeline.ts
- apps/moo-dang/src/shell/types.ts
- apps/moo-dang/src/workers/shell.worker.ts
- Add parseCommandPipeline function to handle command pipelines
- Implement executePipeline function for executing command pipelines
- Create pipeline test suite to validate parsing and execution
- Enhance types for command parsing and I/O redirection
- Integrate pipeline execution in shell worker message handling
Closes #943.
> feat: implement command pipeline execution with I/O redirection

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/wasm-communication.md
- apps/moo-dang/src/shell/wasm-loader.ts
- Create documentation for the shell-to-WASM communication interface.
- Outline bidirectional communication protocols between the shell and WASM modules.
- Define architecture and communication flow examples for clarity.
- Include error handling and performance characteristics for the interface.
Relates to TASK-022 on #944.
> feat: implement shell-to-WASM communication interface

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/wasm-commands.ts
- apps/moo-dang/src/shell/wasm-loader.ts
- apps/moo-dang/src/shell/wasm-types.ts
- apps/moo-dang/src/shell/wasm.test.ts
- Add comprehensive error context for WASM operations.
- Implement enhanced output buffering for large data streams.
- Improve error messages for network and HTTP failures.
- Update tests to validate new error handling features.
Closes #944.
> feat: enhance WASM error handling and output management

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/commands.test.ts
- apps/moo-dang/src/shell/commands.ts
- apps/moo-dang/src/shell/script-executor.ts
- apps/moo-dang/src/shell/script-parser.ts
- apps/moo-dang/src/shell/script-types.ts
- Added `script-executor.ts` for executing shell scripts with support for variable scoping, control flow, function calls, and error handling.
- Introduced `script-parser.ts` for parsing shell script syntax including comments, variable assignments, commands, and control structures.
- Defined structured types in `script-types.ts` for script statements, execution context, and parsing results.
- Enhanced error handling and logging for script execution and parsing processes.
Relates to TASK-026 on #945.
> feat: implement shell script execution engine and parser

- apps/moo-dang/src/hooks/use-command-input.ts
- apps/moo-dang/src/shell/command-help.ts
- apps/moo-dang/src/shell/commands.ts
- apps/moo-dang/src/shell/history-manager.test.ts
- apps/moo-dang/src/shell/history-manager.ts
- apps/moo-dang/src/shell/history-types.ts
- Add `history-manager.ts` for managing command history with persistence, search, and analytics.
- Introduce `history-types.ts` to define types and interfaces for history management.
- Create unit tests in `history-manager.test.ts` to validate functionality including adding, searching, clearing, and exporting history.
- Implement localStorage integration for persistent history across sessions.
- Support for command metadata, duplicate handling, and cleanup of old entries.
- Enhance search capabilities with filters for date range, working directory, and success status.
Relates to TASK-029 on #945.
> feat: implement comprehensive history management for shell commands

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/command-help.ts
- apps/moo-dang/src/shell/commands.ts
- apps/moo-dang/src/shell/config-manager.test.ts
- apps/moo-dang/src/shell/config-manager.ts
- apps/moo-dang/src/shell/config-types.ts
- Add ShellConfigManager for managing shell configurations with localStorage persistence.
- Introduce configuration types and interfaces for better type safety.
- Create a test suite for ShellConfigManager covering initialization, value retrieval, updates, validation, and persistence.
- Implement default configuration values and validation logic for user preferences.
- Support for exporting and importing configurations with metadata.
- Add change listeners for configuration updates and ensure graceful error handling.
Closes #945.
> feat(moo-dang): Implement configuration management

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/src/shell/wasm-commands.ts
- apps/moo-dang/src/shell/wasm-integration.test.ts
- Modify command execution to handle cases with no arguments.
- Add comprehensive integration tests for WASM executable loading and execution.
Relates to TASK-032 on #946.
> feat: update WASM command execution and add integration tests

- apps/moo-dang/src/shell/commands.ts
- apps/moo-dang/src/shell/completion-providers.ts
- apps/moo-dang/src/shell/config-manager.ts
- apps/moo-dang/src/shell/pipeline.ts
- apps/moo-dang/src/shell/virtual-file-system.ts
- Replace ShellCommandError, InvalidArgumentError, and FileOperationError classes with factory functions.
- Update error handling in pipeline and virtual file system to use new error creation functions.
- Refactor completion provider to utilize function-based error creation.
- Enhance localStorage configuration management with improved error handling functions.
> refactor: replace error classes with factory functions for consistency

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/API.md
- apps/moo-dang/ARCHITECTURE.md
- apps/moo-dang/DEVELOPMENT.md
- apps/moo-dang/EXAMPLES.md
- apps/moo-dang/README.md
- Create EXAMPLES.md with practical examples and tutorials for using the moo-dang WASM web shell, covering basic shell navigation, WASM program execution, environment variables, file management, text processing, and advanced workflows.
- Add README.md to provide an overview of the moo-dang project, including features, quick start instructions, usage examples, architecture details, development scripts, testing information, API documentation, and contribution guidelines.
Relates TASK-034 on #946.
> docs(moo-dang): write comprehensive documentation and usage examples

- .ai/plan/feature-moo-dang-shell-1.md
- apps/moo-dang/package.json
- apps/moo-dang/src/hooks/use-command-input.ts
- apps/moo-dang/src/hooks/use-terminal-output.ts
- apps/moo-dang/src/test/command-benchmarks.ts
- apps/moo-dang/src/test/performance-runner.ts
- apps/moo-dang/src/test/terminal-benchmarks.ts
- apps/moo-dang/src/test/wasm-benchmarks.ts
- apps/moo-dang/src/utils/benchmark.ts
- apps/moo-dang/src/utils/output-formatting.ts
- apps/moo-dang/src/utils/performance-optimizations.ts
- pnpm-lock.yaml
- Introduce `wasm-benchmarks.ts` for comprehensive benchmarking of WASM module loading, instantiation, and memory management.
- Implement `benchmark.ts` for performance measurement utilities, including statistical analysis and memory tracking.
- Create `performance-optimizations.ts` for caching, memory pooling, lazy loading, and debouncing strategies to enhance application performance.
- Add optimized caching mechanisms and memory management techniques to reduce garbage collection pressure.
- Establish global optimization instances for shared use across the application.
Closes #946.
> feat: add WASM performance benchmarking suite and utilities

- .ai/plan/refactor-audit-improvements-1.md
- docs/src/content/docs/utils/advanced-patterns.md
- package.json
- packages/theme/docs/EXAMPLES.md
- packages/theme/test/setup.ts
- packages/theme/test/theme-combined.integration.test.tsx
- packages/theme/test/theme-persistence.integration.test.tsx
- packages/ui/src/dev.tsx
- pnpm-lock.yaml
- scripts/enhanced-error-wrapper.ts
- scripts/validate-build.ts
- scripts/validate-exports.ts
- Change status from 'Planned' to 'In Progress' in audit plan
- Update badge to reflect current status in documentation
- Mock console.warn to suppress localStorage-related warnings during tests
- Remove unnecessary console.warn mocks from integration tests
Relates to TASK-001 on #1006.
> refactor: update code audit implementation status and testing setup

- .ai/plan/refactor-audit-improvements-1.md
- apps/moo-dang/src/components/Terminal.test.tsx
- Fix terminal.loadAddon errors in Terminal component tests.
- Update task status in the comprehensive code audit implementation plan.
Relates to TASK-002 on #1006.
> fix: resolve terminal.loadAddon errors in Terminal component tests

- .ai/plan/refactor-audit-improvements-1.md
- packages/ui/test/Form.test.tsx
- packages/ui/test/setup.ts
- Fix hasPointerCapture errors in Radix UI integration tests in packages/ui/test/Form.test.tsx
- Update task status for fixing theme localStorage mock errors and resolving terminal.loadAddon errors
Relates to TASK-003 on #1006.
> fix: resolve hasPointerCapture errors in Radix UI integration tests

- .ai/plan/refactor-audit-improvements-1.md
- .ai/security/localStorage-security-audit-2025-09-30.md
- Update last_updated date in the audit plan
- Mark TASK-008 and TASK-009 as completed in the audit report
- Add comprehensive localStorage security audit report
- Document excellent security practices and compliance status
Closes #1007.
> chore: update localStorage security audit report and tasks

- .ai/plan/refactor-audit-improvements-1.md
- docs-legacy/README.md
- docs/src/content/docs/development/troubleshooting.md
- docs/src/content/docs/development/workflows.md
- packages/config/README.md
- packages/error-testing/README.md
- packages/types/README.md
- packages/utils/README.md
- Audited and migrated content from docs-legacy/ to main docs/ structure.
- Updated JSDoc comments to align with current API signatures.
- Standardized documentation patterns across all packages for consistency.
- Created new README files for @sparkle/config, @sparkle/error-testing, @sparkle/types, and @sparkle/utils packages.
- Added detailed troubleshooting and development workflow guides to enhance developer experience.
- Deprecated the docs-legacy/ directory with a clear migration summary and access instructions.
Relates to TASK-014 and TASK-016 on #1009.
> refactor: complete documentation migration and standardization

- .ai/plan/refactor-audit-improvements-1.md
- .ai/review/task-021-code-review.md
- apps/moo-dang/src/components/Terminal.test.tsx
- packages/test-utils/README.md
- packages/test-utils/package.json
- packages/test-utils/src/console/console-mocks.ts
- packages/test-utils/src/console/index.ts
- packages/test-utils/src/dom/index.ts
- packages/test-utils/src/dom/local-storage.ts
- packages/test-utils/src/dom/media-query.ts
- packages/test-utils/src/dom/resize-observer.ts
- packages/test-utils/src/index.ts
- packages/test-utils/src/lifecycle/index.ts
- packages/test-utils/src/lifecycle/test-lifecycle.ts
- packages/test-utils/src/react/index.ts
- packages/test-utils/src/react/render-utils.tsx
- packages/test-utils/src/terminal/index.ts
- packages/test-utils/src/terminal/xterm-mocks.ts
- packages/test-utils/tsconfig.json
- packages/test-utils/tsdown.config.ts
- pnpm-lock.yaml
- Add @sparkle/test-utils package with utilities for DOM, React, console, terminal, and lifecycle testing.
- Implement mocks for localStorage, MediaQueryList, ResizeObserver, and XTerm.js components.
- Create render utilities for React components with theme support.
- Establish standardized setup and teardown functions for tests.
- Enhance documentation with usage examples and API references.
Relates to TASK-021 on #1010.
> feat(test-utils): introduce shared test utilities

- docs/scripts/generate-theme-css.ts
- docs/src/styles/sparkle-theme.css
- Add detailed documentation for Starlight theme system architecture
- Improve color variable semantics for better readability
- Map tokens for proper contrast in light and dark modes
- Implement special handling for code block backgrounds
- Update UI background and text colors for consistency across themes
> feat: enhance Starlight theme CSS for better light/dark mode support

- .ai/plan/feature-astro-starlight-docs-1.md
- docs/astro.config.mjs
- docs/src/components/demos/ButtonDemo.tsx
- docs/src/components/interactive/StorybookEmbed.tsx
- docs/src/components/interactive/theme-toggle.tsx
- docs/src/components/showcase/ComponentShowcase.tsx
- docs/src/content/docs/guides/aria-labels.mdx
- Update last_updated date in Astro Starlight documentation plan
- Add ARIA labels to interactive components for better accessibility
- Introduce a new guide for ARIA labels and accessibility attributes
- Improve accessibility features in ButtonDemo, ThemeToggle, and ComponentShowcase
- Ensure all interactive elements have descriptive labels and roles
Relates to TASK-038 on #875.
> feat: enhance accessibility across documentation components

- .ai/notes/implementaton-plan-prompts.md
- .github/copilot-instructions.md
- Add essential commands for development workflow
- Include key patterns for component development and naming conventions
- Outline critical principles for project consistency
> docs: expand copilot instructions with essential commands and principles

- .ai/plan/feature-astro-starlight-docs-1.md
- .github/workflows/deploy-docs.yaml
- docs/astro.config.mjs
- docs/package.json
- docs/scripts/build-performance.ts
- docs/src/content/docs/deployment/build-optimization.md
- Implement build optimizations for faster deployment times
- Add performance monitoring script to analyze build metrics
- Configure caching strategies and chunk splitting for improved efficiency
- Create comprehensive build optimization guide for documentation
- Update Astro configuration for better asset management and prefetching
Relates to TASK-044 on #876.
> feat: enhance build performance and optimization strategies

- .ai/plan/feature-astro-starlight-docs-1.md
- .github/workflows/deploy-docs.yaml
- .github/workflows/regenerate-docs.yaml
- docs/src/content/docs/deployment/caching-strategies.md
- Add caching for generated documentation to optimize build times
- Implement caching for Astro build artifacts to improve deployment speed
- Create comprehensive guide on caching strategies for documentation site
- Update workflows to report cache status and improve CI efficiency
Relates to TASK-045 on #876.
> feat: implement caching strategies for documentation builds
